apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-manager
  labels:
    app: {{ .Release.Name }}-manager
spec:
  type: {{ .Values.manager.service.type }}
  ports:
    - port: {{ .Values.manager.service.port }}
      targetPort: {{ .Values.manager.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-manager
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-router
  labels:
    app: {{ .Release.Name }}-router
spec:
  type: {{ .Values.router.service.type }}
  ports:
    - port: {{ .Values.router.service.port }}
      targetPort: {{ .Values.router.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-router
